apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit-service
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8501
  selector:
    app: streamlit-app